export const siteConfig = {
  name: "Meenu's Dosa",
  legalName: "Meenu's Dosa Pure Vegetarian South Indian Restaurant",
  tagline: "Authentic South Indian Cuisine",
  mainHeroHeading: "Hot. Crispy. Authentic.",
  heroSubheading: "Experience the taste of South India at Meenu's Dosa.",
  heritageClaim: "Serving the love of South Indian food for generations.",
  heritageYears: "40+",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://meenusdosa.com",
  ogImage: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=80",
  description:
    "Discover authentic South Indian cuisine at Meenu's Dosa in Bhopal. Explore hot crispy dosas, soft idlis, uttapams and regional delicacies. Pure vegetarian dining, takeaway, online ordering, and table reservations.",
  keywords: [
    "Meenu's Dosa",
    "South Indian restaurant Bhopal",
    "Best dosa in Bhopal",
    "Minal Residency Dosa",
    "MP Nagar South Indian food",
    "Authentic Masala Dosa Bhopal",
    "Pure vegetarian South Indian restaurant",
    "Idli Vada Sambar Bhopal",
    "Meenu's Dosa online order Zomato Swiggy",
  ],
  author: "Meenu's Dosa",
  city: "Bhopal",
  state: "Madhya Pradesh",
  country: "India",
};
